/* Generated By:JavaCC: Do not edit this line. MathParserConstants.java */
package nl.peterbjornx.calclib.parse;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MathParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 2;
  /** RegularExpression Id. */
  int PLUS = 3;
  /** RegularExpression Id. */
  int MINUS = 4;
  /** RegularExpression Id. */
  int TIMES = 5;
  /** RegularExpression Id. */
  int DIVIDE = 6;
  /** RegularExpression Id. */
  int EQUALS = 7;
  /** RegularExpression Id. */
  int CROSS = 8;
  /** RegularExpression Id. */
  int DIFF = 9;
  /** RegularExpression Id. */
  int SDIFF = 10;
  /** RegularExpression Id. */
  int PDIFF = 11;
  /** RegularExpression Id. */
  int CURL = 12;
  /** RegularExpression Id. */
  int DIVG = 13;
  /** RegularExpression Id. */
  int GRAD = 14;
  /** RegularExpression Id. */
  int POWER = 15;
  /** RegularExpression Id. */
  int NUMBER = 16;
  /** RegularExpression Id. */
  int NAME = 17;
  /** RegularExpression Id. */
  int LISTSEP = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<EOL>",
    "\"+\"",
    "\"-\"",
    "<TIMES>",
    "\"/\"",
    "\"=\"",
    "<CROSS>",
    "<DIFF>",
    "\"\\\'\"",
    "\"\\u2202\"",
    "\"\\u2207\\u2a2f\"",
    "\"\\u2207\\u2219\"",
    "\"\\u2207\"",
    "\"^\"",
    "<NUMBER>",
    "<NAME>",
    "<LISTSEP>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"|\"",
  };

}
